---
- become: true
  become_user: root
  block:
  - name: Flush handlers
    meta: flush_handlers
  - name: Ensure Consul is running
    systemd:
      name: consul.service
      state: started
      enabled: yes

