---
- name: Base install
  import_tasks: base-install.yaml

- name: Install certs
  import_tasks: certs.yaml

- name: Ensure Consul is reloaded/running
  import_tasks: flush.yaml

- name: Apply ACLs
  import_tasks: acl.yaml

- name: Ensure Consul is reloaded/running
  import_tasks: flush.yaml

