---
- become: true
  become_user: root
  block:
  - name: Install Consul binary
    copy:
      src: consul
      dest: /usr/local/bin/consul
      mode: 0755
  - name: Create consul user
    user:
      name: consul
      home: /etc/consul.d/
      shell: /bin/false
      system: yes
  - name: Ensure config directory exists
    file:
      path: /etc/consul.d
      state: directory
      owner: consul
      group: consul
    notify: Restart consul
  - name: Apply base config
    template:
      src: 00-base.hcl
      dest: /etc/consul.d/00-base.hcl
      mode: 0640
      owner: consul
      group: consul
    notify: Restart consul
  - name: Apply server config
    template:
      src: 10-server.hcl
      dest: /etc/consul.d/10-server.hcl
      mode: 0640
      owner: consul
      group: consul
    when: is_consul_server
    notify: Restart consul
  - name: Apply client config
    template:
      src: 10-client.hcl
      dest: /etc/consul.d/10-client.hcl
      mode: 0640
      owner: consul
      group: consul
    when: not is_consul_server
    notify: Restart consul
  - name: Add CA public key
    copy:
      src: certs/consul-agent-ca.pem
      dest: /etc/consul.d/ca.pem
      mode: 0644
      owner: consul
      group: consul
  - name: Add server cert public key
    copy:
      src: "certs/{{ datacenter }}-server-consul-{{ consul_cert_index }}.pem"
      dest: /etc/consul.d/cert.pem
      mode: 0644
      owner: consul
      group: consul
    when: is_consul_server
  - name: Add server cert private key
    copy:
      src: "certs/{{ datacenter }}-server-consul-{{ consul_cert_index }}-key.pem"
      dest: /etc/consul.d/cert-key.pem
      mode: 0644
      owner: consul
      group: consul
    when: is_consul_server
  - name: Ensure data directory exists
    file:
      path: /opt/consul
      state: directory
      owner: consul
      group: consul
    notify: Restart consul
  - name: Install Consul service
    copy:
      src: consul.service
      dest: /etc/systemd/system/consul.service
    notify: Restart consul
  - name: Flush handlers
    meta: flush_handlers
  - name: Ensure Consul is running
    systemd:
      name: consul.service
      state: started
      enabled: yes

