---
managed_groups:
  - name: boss
  - name: hero
  - name: enemy
managed_users:
  - name: bowser
    groups: boss, enemy
  - name: mario
    groups: hero
  - name: luigi
    groups: hero
  - name: peach
    groups: hero
  - name: wario
    groups: enemy

# This is enabled for the SSH sample, but this is NOT a good security practice!
nomad_raw_exec_enabled: true
