---
- become: true
  become_user: root
  block:
  - name: Render server.hcl
    template:
      src: server.hcl
      dest: /etc/nomad.d/server.hcl
    notify: Restart service
  - name: Copy nomad.service
    copy:
      src: nomad.service
      dest: /etc/systemd/system/nomad.service
    notify: Restart service
  - name: Flush handlers
    meta: flush_handlers
  - name: Ensure service is enabled and running
    systemd:
      name: nomad.service
      enabled: yes
      state: started

