---
- name: Install Weave
  become: true
  become_user: root
  block:
  - name: Download Weave
    get_url:
      url: https://git.io/weave
      dest: /usr/local/bin/weave
      mode: '0755'
  - name: Add vagrant user to Docker group
    user:
      name: vagrant
      state: present
      groups: docker
