---
- become: true
  become_user: root
  block:
  - name: Install Nomad
    copy:
      src: nomad
      dest: /usr/local/bin/nomad
      mode: 0755
  - name: Ensure data directory exists
    file:
      path: /opt/nomad
      state: directory
  - name: Ensure Nomad config directory exists
    file:
      path: /etc/nomad.d
      state: directory
  - name: Copy data dir configuration
    copy:
      src: data-dir.hcl
      dest: /etc/nomad.d/data-dir.hcl
  - name: Render advertise config
    template:
      src: advertise.hcl
      dest: /etc/nomad.d/advertise.hcl
  - name: Copy nomad.service
    copy:
      src: nomad.service
      dest: /etc/systemd/system/nomad.service
    notify: Restart nomad
  - name: Flush handlers
    meta: flush_handlers
  - name: Ensure service is enabled
    systemd:
      name: nomad.service
      enabled: yes
      state: started


