---
- become: true
  become_user: root
  block:
  - name: Install Nomad binary
    copy:
      src: nomad
      dest: /usr/local/bin/nomad
      mode: 0755
    notify: Restart nomad
  - name: Ensure data directory exists
    file:
      path: /opt/nomad
      state: directory
  - name: Ensure Nomad config directory exists
    file:
      path: /etc/nomad.d
      state: directory
  - name: Render base config
    template:
      src: 00-base.hcl
      dest: /etc/nomad.d/00-base.hcl
    notify: Restart nomad

  # NOTE: theoretically we could have nodes that are both servers and clients,
  # but Nomad recommends against this in production for various good reasons.
  # Even though this is a toy sandbox we're going to take this advice and make
  # a server and client mutually exclusive.  We include the removal step to be
  # safe in case something is rendered accidentally, or if a node switches roles.
  - name: Nomad Server
    when: is_nomad_server
    block:
    - name: Render server config
      template:
        src: 10-server.hcl
        dest: /etc/nomad.d/10-server.hcl
      notify: Restart nomad
    - name: Remove client config from servers
      file:
        path: /etc/nomad.d/10-client.hcl
        state: absent
      notify: Restart nomad
  - name: Nomad Client
    when: is_nomad_server != true
    block:
    - name: Remove server config from clients
      file:
        path: /etc/nomad.d/10-server.hcl
        state: absent
      notify: Restart nomad
    - name: Render client config
      template:
        src: 10-client.hcl
        dest: /etc/nomad.d/10-client.hcl
      notify: Restart nomad
    - name: Ensure plugin directory exists
      file:
        path: /opt/nomad/plugins
        state: directory
    - name: Install generic device plugin
      unarchive:
        src: https://github.com/Evertras/nomad-generic-device-plugin/releases/download/v{{ generic_device_plugin_version }}/nomad-generic-device-plugin_{{ generic_device_plugin_version }}_linux_amd64.tar.gz
        dest: /opt/nomad/plugins/
        include:
          - generic-device
        remote_src: yes
      notify: Restart nomad
    - name: Render device config
      template:
        src: 20-device.hcl
        dest: /etc/nomad.d/20-device.hcl
      notify: Restart nomad

  - name: Render nomad.service
    template:
      src: nomad.service
      dest: /etc/systemd/system/nomad.service
    notify: Restart nomad

  # If we've been notified to restart nomad, now is the time to do it...
  - name: Flush handlers
    meta: flush_handlers

  - name: Ensure service is enabled
    systemd:
      name: nomad.service
      enabled: yes
      state: started

