---
- become: true
  become_user: root
  block:
  - name: Install Nomad
    copy:
      src: nomad
      dest: /usr/local/bin/nomad
      mode: 0755
  - name: Ensure data directory exists
    file:
      path: /opt/nomad
      state: directory
  - name: Ensure Nomad config directory exists
    file:
      path: /etc/nomad.d
      state: directory
  - name: Render base config
    template:
      src: 00-base.hcl
      dest: /etc/nomad.d/00-base.hcl
    notify: Restart nomad
  - name: Render server config
    template:
      src: 10-server.hcl
      dest: /etc/nomad.d/10-server.hcl
    when: nomad_server is defined and nomad_server == 'true'
    notify: Restart nomad
  - name: Render client config
    template:
      src: 10-client.hcl
      dest: /etc/nomad.d/10-client.hcl
    when: nomad_server is not defined or nomad_server != 'true'
    notify: Restart nomad
  - name: Copy nomad.service
    copy:
      src: nomad.service
      dest: /etc/systemd/system/nomad.service
    notify: Restart nomad
  - name: Flush handlers
    meta: flush_handlers
  - name: Ensure service is enabled
    systemd:
      name: nomad.service
      enabled: yes
      state: started

