lakitus:
  hosts:
    lakitu:
      ansible_host: 192.168.56.2
      ansible_ssh_private_key_file: ../.vagrant/machines/lakitu/virtualbox/private_key 
      advertise_ip: 192.168.56.2
      # TODO: this doesn't feel good
      consul_cert_index: 0
  vars:
    ansible_user: vagrant
    is_consul_server: true
    is_nomad_server: true
    datacenter: mushroom-kingdom
    managed_groups:
      - name: boss
      - name: enemy
    managed_users:
      - name: bowser
        groups: boss, enemy

spineys:
  hosts:
    spiney1:
      ansible_host: 192.168.56.3
      ansible_ssh_private_key_file: ../.vagrant/machines/spiney1/virtualbox/private_key 
      advertise_ip: 192.168.56.3
    spiney2:
      ansible_host: 192.168.56.4
      ansible_ssh_private_key_file: ../.vagrant/machines/spiney2/virtualbox/private_key 
      advertise_ip: 192.168.56.4
  vars:
    ansible_user: vagrant
    datacenter: mushroom-kingdom
    managed_groups:
      - name: boss
      - name: hero
      - name: enemy
    managed_users:
      - name: bowser
        groups: boss, enemy
      - name: mario
        groups: hero
      - name: luigi
        groups: hero
      - name: peach
        groups: hero
      - name: wario
        groups: enemy 
