---
- hosts: lakitus, spineys
  roles:
    - base
    - users
    - cyn
    - role: geerlingguy.docker
      become: true
      vars:
        docker_daemon_options:
          registry-mirrors: "{{ [lakitu_docker_registry_mirror] if lakitu_docker_registry_mirror else [] }}"
          icc: false
    - consul
    - nomad
    - vault
    - weave
