---
- hosts: lakitus, spineys
  tasks:
    - name: Update apt cache
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 86400
    - name: Install some useful packages
      become: true
      apt:
        pkg:
          - jq
- hosts: lakitus, spineys
  roles:
    - fx
    - users
    - role: geerlingguy.docker
      become: true
    - consul
    - nomad
    - vault
    - weave
