---
- become: true
  become_user: root
  vars:
    nomad_servers: "{{ groups['lakitus'] }}"
  block:
  - name: Render client.hcl
    template:
      src: client.hcl
      dest: /etc/nomad.d/client.hcl
    notify: Restart nomad

